### PR TITLE
add merge option deep_all to be used with keyless lookups

### PR DESCRIPTION
**Pull request by msutter**
by using keyless lookups with cascade and merge set to array/hash/deep_hash, each found key will try to merge its values, resulting in type errors for strings, ints, etc...

This PR checks the type and adds a 'deep_all' option to be used for merge, which will deep_merge all hashes and arrays. Standard usage of the merge options should work as always. (Not sure about this as I'm really new to jerakia)

### CODE REVIEW

**Comment by msutter** [comment]
I'll write some tests for it, and fix the failed checks

**Comment by msutter** [comment]
@crayfishx question: by cascade merging with array merge, should keys with values of type int, string, bool be all added to a resulting array ? For me it doesn't make sense to change the type of the resulting value, but need confirmation that this is not needed elsewhere.

**Comment by crayfishx** [comment]
The original idea around keyless was to rely on schemas for determining behaviour - it makes more sense to restrict the use of the lookup options array, hash, deep_hash to key lookups..... but Im happy to discuss this.

**Comment by beddari** [comment]
I agree with Craig that this should be tied to schemas ...

**Comment by beddari** [comment]
This won't be merged for now, but please discuss it further in a ticket ...

**Pull request closed without merging**
